name: Deploy Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Update Website
        run: |
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} '
            cd ~/projects/nginx_webpage &&
            git fetch origin
            git reset --hard origin/master

            if podman container exists nginx_webpage; then
                podman start nginx_webpage || true
            else
                podman run -d \
                --name nginx_webpage
                --restart=always \
                -p 8080:80 \
                -v ~/projects/nginx_webpage:/usr/share/nginx/html:ro \
                docker.io/library/nginx:alpine
            fi
          '